// The Birthday Dossier — on-device numerology, star charts and horoscopes.
//
// House rules, same as the number generator downstairs:
//   • The FACTS are real. Star sign dates, Chinese zodiac years (lunar-new-year
//     accurate), birthstones, birth flowers — all correct, because people who
//     care about these things deserve to see them done properly.
//   • The MEANINGS are decorative. All of them. The horoscope is generated by
//     arithmetic wearing a dressing gown.
//   • Nothing leaves the device. No network, no analytics payloads, nothing.
//     A test enforces this. The cosmos operates strictly offline.

import { track } from '../services/analytics';

const LOCAL_KEY = 'dossier-prefs';

/* ======================================================================
   REAL FACTS (kept accurate on purpose)
   ====================================================================== */

interface StarSign {
	name: string;
	glyph: string;
	from: readonly [number, number]; // month, day (inclusive start)
	blurb: string;
}

// Western tropical dates, conventional boundaries. Ordered from Capricorn so
// lookup is a simple scan (Capricorn wraps the year end).
const STAR_SIGNS: readonly StarSign[] = [
	{ name: 'Capricorn', glyph: '♑', from: [12, 22], blurb: 'Climbing something as we speak. Probably a career.' },
	{ name: 'Aquarius', glyph: '♒', from: [1, 20], blurb: 'Ahead of their time, and slightly to the left of it.' },
	{ name: 'Pisces', glyph: '♓', from: [2, 19], blurb: 'Swimming in both directions at once, elegantly.' },
	{ name: 'Aries', glyph: '♈', from: [3, 21], blurb: 'First into everything, including this sentence.' },
	{ name: 'Taurus', glyph: '♉', from: [4, 20], blurb: 'Immovable object; negotiable if snacks are involved.' },
	{ name: 'Gemini', glyph: '♊', from: [5, 21], blurb: 'Two for the price of one. Both of you are welcome here.' },
	{ name: 'Cancer', glyph: '♋', from: [6, 21], blurb: 'Armoured exterior, gooey centre. The cosmos respects the shell.' },
	{ name: 'Leo', glyph: '♌', from: [7, 23], blurb: 'Main character energy, officially licensed.' },
	{ name: 'Virgo', glyph: '♍', from: [8, 23], blurb: 'Has already spotted the typo in this dossier.' },
	{ name: 'Libra', glyph: '♎', from: [9, 23], blurb: 'Perfectly balanced. Took four hours to decide that.' },
	{ name: 'Scorpio', glyph: '♏', from: [10, 23], blurb: 'Intense. The stars would say more, but they’re a little scared.' },
	{ name: 'Sagittarius', glyph: '♐', from: [11, 22], blurb: 'Currently planning a trip. The arrow has already left.' }
];

function starSignFor(month: number, day: number): StarSign {
	// walk backwards through start dates; first one we're on/after wins
	for (let i = STAR_SIGNS.length - 1; i >= 0; i--) {
		const [m, d] = STAR_SIGNS[i].from;
		if (month > m || (month === m && day >= d)) return STAR_SIGNS[i];
	}
	return STAR_SIGNS[0]; // Jan 1–19 → Capricorn (wrapped)
}

// Chinese New Year, Gregorian dates, 1920–2030. The zodiac year begins HERE,
// not on Jan 1 — January/February birthdays belong to the previous animal if
// they fall before this date. Sourced table injected below (see CNY_DATES).
// Cross-checked against Hong Kong Observatory calendars (see PR notes).
const CNY_DATES: readonly string[] = [
	'1920-02-20', '1921-02-08', '1922-01-28', '1923-02-16', '1924-02-05', '1925-01-24',
	'1926-02-13', '1927-02-02', '1928-01-23', '1929-02-10', '1930-01-30', '1931-02-17',
	'1932-02-06', '1933-01-26', '1934-02-14', '1935-02-04', '1936-01-24', '1937-02-11',
	'1938-01-31', '1939-02-19', '1940-02-08', '1941-01-27', '1942-02-15', '1943-02-05',
	'1944-01-25', '1945-02-13', '1946-02-02', '1947-01-22', '1948-02-10', '1949-01-29',
	'1950-02-17', '1951-02-06', '1952-01-27', '1953-02-14', '1954-02-03', '1955-01-24',
	'1956-02-12', '1957-01-31', '1958-02-18', '1959-02-08', '1960-01-28', '1961-02-15',
	'1962-02-05', '1963-01-25', '1964-02-13', '1965-02-02', '1966-01-21', '1967-02-09',
	'1968-01-30', '1969-02-17', '1970-02-06', '1971-01-27', '1972-02-15', '1973-02-03',
	'1974-01-23', '1975-02-11', '1976-01-31', '1977-02-18', '1978-02-07', '1979-01-28',
	'1980-02-16', '1981-02-05', '1982-01-25', '1983-02-13', '1984-02-02', '1985-02-20',
	'1986-02-09', '1987-01-29', '1988-02-17', '1989-02-06', '1990-01-27', '1991-02-15',
	'1992-02-04', '1993-01-23', '1994-02-10', '1995-01-31', '1996-02-19', '1997-02-07',
	'1998-01-28', '1999-02-16', '2000-02-05', '2001-01-24', '2002-02-12', '2003-02-01',
	'2004-01-22', '2005-02-09', '2006-01-29', '2007-02-18', '2008-02-07', '2009-01-26',
	'2010-02-14', '2011-02-03', '2012-01-23', '2013-02-10', '2014-01-31', '2015-02-19',
	'2016-02-08', '2017-01-28', '2018-02-16', '2019-02-05', '2020-01-25', '2021-02-12',
	'2022-02-01', '2023-01-22', '2024-02-10', '2025-01-29', '2026-02-17', '2027-02-06',
	'2028-01-26', '2029-02-13', '2030-02-03'
];
const CNY_BASE_YEAR = 1920;

const ZODIAC_ANIMALS: readonly { name: string; glyph: string; blurb: string }[] = [
	{ name: 'Rat', glyph: '🐀', blurb: 'Resourceful. Was here before you and will outlast the building.' },
	{ name: 'Ox', glyph: '🐂', blurb: 'Unstoppable, eventually. The tortoise’s hero.' },
	{ name: 'Tiger', glyph: '🐅', blurb: 'Brave to a degree the paperwork calls “noteworthy”.' },
	{ name: 'Rabbit', glyph: '🐇', blurb: 'Gentle, quick, and always near an exit. Wise.' },
	{ name: 'Dragon', glyph: '🐉', blurb: 'The only mythical option, and fully aware of it.' },
	{ name: 'Snake', glyph: '🐍', blurb: 'Thinks before speaking. Sometimes for years.' },
	{ name: 'Horse', glyph: '🐎', blurb: 'Free-spirited. Fences are a suggestion.' },
	{ name: 'Goat', glyph: '🐐', blurb: 'Creative, kind, and better at climbing than you’d think.' },
	{ name: 'Monkey', glyph: '🐒', blurb: 'Clever enough to get into trouble and out of it, in that order.' },
	{ name: 'Rooster', glyph: '🐓', blurb: 'Punctual, observant, and correct slightly too often.' },
	{ name: 'Dog', glyph: '🐕', blurb: 'Loyal. If the cosmos had a best friend.' },
	{ name: 'Pig', glyph: '🐖', blurb: 'Generous and honest. The zodiac’s good news.' }
];

// element cycle by the zodiac year's last digit (also bounded by CNY)
const ELEMENTS: Record<number, string> = {
	0: 'Metal', 1: 'Metal', 2: 'Water', 3: 'Water', 4: 'Wood',
	5: 'Wood', 6: 'Fire', 7: 'Fire', 8: 'Earth', 9: 'Earth'
};

/** The zodiac year a Gregorian date belongs to (lunar-new-year accurate). */
function zodiacYearFor(date: Date): number {
	const y = date.getFullYear();
	const cny = CNY_DATES[y - CNY_BASE_YEAR];
	if (!cny) return y; // outside table — degrade to calendar year
	// compare LOCAL date parts — toISOString() is UTC and can drift a day
	const iso = `${y}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
	return iso < cny ? y - 1 : y;
}

function chineseZodiacFor(date: Date): { animal: (typeof ZODIAC_ANIMALS)[number]; element: string; year: number } {
	const year = zodiacYearFor(date);
	const idx = (((year - 1924) % 12) + 12) % 12; // 1924 = Rat
	return { animal: ZODIAC_ANIMALS[idx], element: ELEMENTS[year % 10], year };
}

const BIRTHSTONES: readonly string[] = [
	'Garnet', 'Amethyst', 'Aquamarine', 'Diamond', 'Emerald', 'Pearl',
	'Ruby', 'Peridot', 'Sapphire', 'Opal', 'Topaz', 'Turquoise'
];

const BIRTH_FLOWERS: readonly string[] = [
	'Carnation', 'Violet', 'Daffodil', 'Daisy', 'Lily of the Valley', 'Rose',
	'Larkspur', 'Gladiolus', 'Aster', 'Marigold', 'Chrysanthemum', 'Narcissus'
];

/* ======================================================================
   NUMEROLOGY (deterministic; the numbers still don't know they're being judged)
   ====================================================================== */

// classic reduction, preserving the "master numbers" — numerology tradition
// says 11, 22 and 33 are exempt from arithmetic, which is a superb rule
function reduceKeepMasters(n: number): number {
	while (n > 9 && n !== 11 && n !== 22 && n !== 33) {
		let s = 0;
		for (const d of String(n)) s += Number(d);
		n = s;
	}
	return n;
}

export function lifePath(date: Date): number {
	const digits = `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}${String(date.getDate()).padStart(2, '0')}`;
	let s = 0;
	for (const d of digits) s += Number(d);
	return reduceKeepMasters(s);
}

// Pythagorean letter values: A=1..I=9, J=1..R=9, S=1..Z=8
export function nameNumber(name: string): number {
	let s = 0;
	for (const ch of name.toUpperCase()) {
		const c = ch.charCodeAt(0);
		if (c >= 65 && c <= 90) s += ((c - 65) % 9) + 1;
	}
	return s ? reduceKeepMasters(s) : 0;
}

const NUMBER_MEANINGS: Record<number, string> = {
	1: 'The Pioneer. Goes first, apologises later.',
	2: 'The Diplomat. Has never lost an argument, technically, because none ever started.',
	3: 'The Spark. Makes things, then makes things of the leftovers.',
	4: 'The Builder. Trusts foundations, spreadsheets and load-bearing walls.',
	5: 'The Wanderer. Owns luggage with genuine mileage.',
	6: 'The Keeper. The friend other friends are assigned to.',
	7: 'The Seeker. Asks the big questions; politely ignores the small answers.',
	8: 'The Engine. Momentum with a calendar.',
	9: 'The Lantern. Lights rooms, asks nothing, leaves them warmer.',
	11: 'The Visionary. Sees it before it exists, which complicates meetings.',
	22: 'The Master Builder. Like the Builder, but with planning permission from fate.',
	33: 'The Master Teacher. So rare the cosmos double-checks the paperwork.'
};

/* ======================================================================
   THE HOROSCOPE ENGINE (arithmetic in a dressing gown)
   ====================================================================== */

// Mulberry-32 again — same honest PRNG the number generator uses
function mulberry32(seed: number): () => number {
	return () => {
		let t = (seed += 0x6d2b79f5);
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

const OMENS: readonly string[] = [
	'The moon is in Uranus, which explains a lot.',
	'Mercury is in retrograde. This affects you 3% more than average (source: the owls).',
	'Venus has entered your billing cycle.',
	'Three magpies were consulted; two agreed.',
	'Your ruling planet filed its paperwork on time today, which is rare.',
	'The stars have aligned — not for you specifically, but you may stand near them.',
	'Saturn is doing that thing again.',
	'A comet you will never see is nonetheless rooting for you.',
	'Jupiter looms auspiciously, as is its habit.',
	'The cosmos checked your file twice today and made a small approving noise.',
	'Today’s planetary alignment spells something rude in Morse code.',
	'The Schumann resonance is holding steady at 7.83 Hz. Reassuring, that.'
];

const HEDGES: readonly string[] = [
	'Expect the unexpected, within reason.',
	'A surprise is possible, though not guaranteed, weather permitting.',
	'Something will happen today. This much is certain.',
	'Change is coming — possibly loose.',
	'An opportunity will knock, or at the very least text.',
	'You will meet someone today. Statistically, several someones.',
	'A door will close; a window will require maintenance.',
	'Good news is travelling toward you at the speed of news.',
	'The answer you seek is inside you, or possibly in your other jacket.',
	'Fortune favours you, pending review.'
];

const ADVICE: readonly string[] = [
	'Do not sign anything with a glitter pen.',
	'Say yes to the second thing, not the first.',
	'Hydrate before the cosmos makes things weird.',
	'Trust your gut, but have your brain countersign.',
	'Avoid land wars and reply-all.',
	'Wear the good socks. You know the ones.',
	'Compliment a stranger’s dog; the dividends compound.',
	'Back up your files and your feelings.',
	'Take the scenic route, though not before 9am.',
	'If in doubt, the button upstairs remains extremely pressable.',
	'Let the phone ring twice before answering. Mystery matters.',
	'Eat something green that is not a sweet.'
];

const LUCKY_OBJECTS: readonly string[] = [
	'a slightly bent paperclip',
	'the third pocket you check',
	'a lift that arrives immediately',
	'an unexpectedly crisp apple',
	'exact change',
	'a pen that works first time',
	'the good trolley',
	'a queue that moves',
	'a round number',
	'a parking space (figuratively yours)',
	'the last one in the box',
	'a green light you didn’t have to earn'
];

export interface Horoscope {
	omen: string;
	hedge: string;
	advice: string;
	luckyObject: string;
	luckyTime: string;
}

/** Deterministic per sign per day — everyone sharing your sign shares your
 *  fate today, which is exactly how this industry has always worked. */
export function dailyHoroscope(signIndex: number, dayIndex: number): Horoscope {
	const rng = mulberry32((signIndex + 1) * 0x9e3779b9 + dayIndex);
	const pick = <T>(arr: readonly T[]): T => arr[Math.floor(rng() * arr.length)];
	const h = Math.floor(rng() * 24);
	const m = Math.floor(rng() * 60);
	return {
		omen: pick(OMENS),
		hedge: pick(HEDGES),
		advice: pick(ADVICE),
		luckyObject: pick(LUCKY_OBJECTS),
		luckyTime: `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`
	};
}

/* ======================================================================
   THE DOSSIER ITSELF
   ====================================================================== */

interface SavedPrefs {
	dob?: string;
	name?: string;
}

export function initDossier(opts: { onFirstDossier?: () => void } = {}): void {
	const root = document.getElementById('luck-dossier');
	const dobInput = document.getElementById('dossier-dob') as HTMLInputElement | null;
	const nameInput = document.getElementById('dossier-name') as HTMLInputElement | null;
	const goBtn = document.getElementById('dossier-go') as HTMLButtonElement | null;
	const burnBtn = document.getElementById('dossier-burn') as HTMLButtonElement | null;
	const out = document.getElementById('dossier-out');
	if (!root || !dobInput || !nameInput || !goBtn || !burnBtn || !out) return;

	// sensible bounds: the table starts in 1920; the future has no birthdays yet
	dobInput.min = '1920-01-01';
	dobInput.max = new Date().toISOString().slice(0, 10);

	let everCompiled = false;
	try {
		const saved = JSON.parse(localStorage.getItem(LOCAL_KEY) || '{}') as SavedPrefs;
		if (typeof saved.dob === 'string' && saved.dob) {
			dobInput.value = saved.dob;
			if (typeof saved.name === 'string') nameInput.value = saved.name.slice(0, 80);
			everCompiled = true;
		}
	} catch { /* corrupt prefs — the cosmos starts a fresh file */ }

	const row = (label: string, value: string, note?: string): HTMLElement => {
		const li = document.createElement('li');
		li.className = 'dossier-row';
		const dt = document.createElement('span');
		dt.className = 'dossier-key';
		dt.textContent = label;
		const dd = document.createElement('span');
		dd.className = 'dossier-value';
		dd.textContent = value;
		li.append(dt, dd);
		if (note) {
			const small = document.createElement('span');
			small.className = 'dossier-note';
			small.textContent = note;
			li.appendChild(small);
		}
		return li;
	};

	function render(): boolean {
		const dob = dobInput!.value;
		if (!dob) return false;
		const date = new Date(`${dob}T12:00:00`); // noon dodges TZ edges
		if (Number.isNaN(+date) || dob < dobInput!.min || dob > dobInput!.max) return false;
		const name = nameInput!.value.trim().slice(0, 80);

		const month = date.getMonth(); // 0-based
		const sign = starSignFor(month + 1, date.getDate());
		const zodiac = chineseZodiacFor(date);
		const lp = lifePath(date);
		const nn = name ? nameNumber(name) : 0;
		const signIdx = STAR_SIGNS.indexOf(sign);
		const scope = dailyHoroscope(signIdx, Math.floor(Date.now() / 86400000));

		out!.textContent = '';
		const card = document.createElement('div');
		card.className = 'dossier-card';

		const h = document.createElement('h3');
		h.className = 'dossier-title';
		h.textContent = `OFFICIAL LUCK DOSSIER — ${name ? name.toUpperCase() : 'THE BEARER'}`;
		card.appendChild(h);

		const list = document.createElement('ul');
		list.className = 'dossier-list';
		list.append(
			row('Star sign', `${sign.glyph} ${sign.name}`, sign.blurb),
			row('Chinese zodiac', `${zodiac.animal.glyph} ${zodiac.element} ${zodiac.animal.name} (${zodiac.year})`, zodiac.animal.blurb),
			row('Birthstone', BIRTHSTONES[month], 'Wearing it is optional; the stone doesn’t mind either way.'),
			row('Birth flower', BIRTH_FLOWERS[month], 'Botanically real. Cosmically decorative.'),
			row('Life path', String(lp), NUMBER_MEANINGS[lp])
		);
		if (nn) list.appendChild(row('Name number', String(nn), `${NUMBER_MEANINGS[nn]} The letters knew before you did.`));
		card.appendChild(list);

		const scopeEl = document.createElement('p');
		scopeEl.className = 'dossier-scope';
		scopeEl.textContent = `TODAY’S FORECAST — ${scope.omen} ${scope.hedge} ${scope.advice}`;
		card.appendChild(scopeEl);

		const lucky = document.createElement('p');
		lucky.className = 'dossier-lucky';
		lucky.textContent = `Lucky object: ${scope.luckyObject}. Lucky time: ${scope.luckyTime}.`;
		card.appendChild(lucky);

		const share = document.createElement('p');
		share.className = 'dossier-small';
		share.textContent = `This forecast is shared with everyone born under ${sign.name}. Fortune-wise, you’re a co-op.`;
		card.appendChild(share);

		out!.appendChild(card);
		burnBtn!.hidden = false;
		return true;
	}

	goBtn.addEventListener('click', () => {
		if (!render()) {
			out!.textContent = '';
			const p = document.createElement('p');
			p.className = 'dossier-small';
			p.textContent = 'The cosmos needs a real birthday to work with. It checked twice.';
			out!.appendChild(p);
			return;
		}
		try {
			localStorage.setItem(LOCAL_KEY, JSON.stringify({ dob: dobInput.value, name: nameInput.value.trim().slice(0, 80) }));
		} catch { /* storage full — the dossier lives for this visit only */ }
		// usage signal only — the payload is deliberately empty. No birthday, no
		// name, no sign, nothing derived from them. A test enforces this.
		track('dossier_generated');
		if (!everCompiled) {
			everCompiled = true;
			try {
				opts.onFirstDossier?.(); // charm ceremony needs the WebGL scene…
			} catch { /* …but the dossier itself never depends on it */ }
		}
	});

	burnBtn.addEventListener('click', () => {
		localStorage.removeItem(LOCAL_KEY);
		dobInput.value = '';
		nameInput.value = '';
		out!.textContent = '';
		const p = document.createElement('p');
		p.className = 'dossier-small';
		p.textContent = 'Dossier burned. The cosmos has already forgotten you were ever born. (So has this device.)';
		out!.appendChild(p);
		burnBtn.hidden = true;
		track('dossier_burned'); // again: event only, no payload
	});

	// a returning visitor's dossier reappears without ceremony (or analytics)
	if (everCompiled) render();
}
